name: ui_kit
description: UI Kit package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  assets: 
    path: ../assets
  flutter_svg: ^2.2.1
  pin_code_fields: ^8.0.1
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
